import 'dart:async';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:nexora_app/core/accounting.dart';
import 'package:nexora_app/core/database.dart';
import 'package:nexora_app/core/format.dart';
import 'package:nexora_app/core/models.dart';
import 'package:nexora_app/data/repository.dart';
import 'package:nexora_app/data/sync/apply_remote.dart';
import 'package:nexora_app/data/sync/conflict_resolver.dart';
import 'package:nexora_app/data/sync/operation.dart';
import 'package:nexora_app/data/sync/recorder.dart';
import 'package:nexora_app/data/sync/sync_engine.dart';
import 'package:nexora_app/data/sync/sync_queue.dart';
import 'package:sqflite_common_ffi/sqflite_ffi.dart';

final _now = DateTime(2026, 9, 6, 12);
Account _account() => Account(
      name: 'عميل QA',
      kind: AccountKind.customer,
      openingBalance: 100,
      notifyChannel: 'none',
      createdAt: _now,
      updatedAt: _now,
    );
Tx _tx(int accountId,
        {double amount = 500,
        OpType type = OpType.debit,
        int? from,
        int? to,
        double rate = 1}) =>
    Tx(
      accountId: type == OpType.transfer ? null : accountId,
      type: type,
      amount: amount,
      fromId: from,
      toId: to,
      rate: rate,
      date: _now,
      createdAt: _now,
      updatedAt: _now,
    );

class TestTransport implements SyncTransport {
  @override
  final String targetId;
  TestTransport([this.targetId = SyncTarget.cloud]);
  Completer<void>? gate;
  final started = Completer<void>();
  Object? error;
  int calls = 0;
  @override
  Future<void> push(SyncOperation operation) async {
    calls++;
    if (!started.isCompleted) started.complete();
    if (gate != null) await gate!.future;
    if (error != null) throw error!;
  }
}

class PermissionFaultRepo extends Repo {
  @override
  Future<AppUser?> currentUser() async =>
      throw const FormatException('QA user lookup fault');
}

void main() {
  sqfliteFfiInit();
  databaseFactory = databaseFactoryFfi;
  late Directory tmp;
  late Database db;
  late Repo repo;
  late int accountId;
  late SyncEngine engine;

  setUp(() async {
    tmp = await Directory.systemTemp.createTemp('nexora_qa_');
    db = await databaseFactory.openDatabase('${tmp.path}/qa.db',
        options: OpenDatabaseOptions(
          onConfigure: (db) => db.execute('PRAGMA foreign_keys = ON'),
        ));
    await AppDatabase.createSchema(db);
    AppDatabase.overrideForTest(db);
    repo = Repo();
    await repo.initSyncInfra(); // (دفعة 57) هوية الجهاز إلزامية قبل الكتابة.
    SyncRecorder.onOperationRecorded = null;
    accountId = await repo.saveAccount(_account());
    engine = SyncEngine(repo: repo, dbProvider: () async => db);
    // Isolate operations generated by the fixture itself.
    await db.delete('sync_queue');
    await db.delete('operations');
    await db.delete('activity');
  });
  tearDown(() async {
    engine.stop();
    SyncRecorder.onOperationRecorded = null;
    if (db.isOpen) await db.close();
    await tmp.delete(recursive: true);
  });

  test('QA-DB-01 offline save persists transaction, queue and invoice together',
      () async {
    await db.insert('sync_meta', {'key': 'workspaceMode', 'value': 'host'},
        conflictAlgorithm: ConflictAlgorithm.replace);
    final id = await repo.saveTx(_tx(accountId));
    expect((await repo.transactions()).single.id, id);
    expect((await repo.transactions()).single.syncState, 'pending');
    expect(await repo.balanceOf((await repo.account(accountId))!), 600);
    expect(await db.query('operations'), hasLength(1));
    expect(await db.query('sync_queue'), isNotEmpty);
    await db.close();
    db = await databaseFactory.openDatabase('${tmp.path}/qa.db');
    AppDatabase.overrideForTest(db);
    expect((await Repo().transactions()).single.id, id);
  });

  test(
      'QA-DB-02 activity failure cannot report failure after money was committed',
      () async {
    await db.execute(
        "CREATE TRIGGER qa_activity_failure BEFORE INSERT ON activity BEGIN SELECT RAISE(ABORT, 'QA activity rejected'); END");
    await expectLater(repo.saveTx(_tx(accountId)), throwsA(anything));
    expect(await repo.transactions(), isEmpty,
        reason: 'Failure must roll back the complete logical save');
    expect(await db.query('operations'), isEmpty);
    expect(await db.query('sync_queue'), isEmpty);
  });

  test('QA-DB-03 deleted transactions are excluded from aggregate balances',
      () async {
    final id = await repo.saveTx(_tx(accountId));
    final a = (await repo.account(accountId))!;
    await repo.deleteTx(id);
    expect(await repo.balanceOf(a), 100);
    expect((await repo.allBalances([a]))[accountId], 100);
  });

  test('QA-DB-04 sequence reservations are unique under concurrent saves',
      () async {
    await Future.wait(List.generate(8, (_) => repo.saveTx(_tx(accountId))));
    final rows = await repo.transactions();
    expect(rows, hasLength(8));
    expect(rows.map((t) => t.reference).toSet(), hasLength(8));
  });

  for (final amount in [0.0, -1.0, double.nan, double.infinity]) {
    test('QA-DB-05 invalid amount $amount must not commit', () async {
      await expectLater(
          repo.saveTx(_tx(accountId, amount: amount)), throwsA(anything));
      expect(await repo.transactions(), isEmpty);
    });
  }

  test(
      'QA-DB-06 self transfer and zero exchange rate are rejected by repository',
      () async {
    await expectLater(
        repo.saveTx(_tx(accountId,
            type: OpType.transfer, from: accountId, to: accountId)),
        throwsA(anything));
    await expectLater(
        repo.saveTx(_tx(accountId,
            type: OpType.transfer, from: accountId, to: accountId, rate: 0)),
        throwsA(anything));
    expect(await repo.transactions(), isEmpty);
  });

  test('QA-PERM-01 authorization lookup failure cannot silently grant access',
      () async {
    final fault = PermissionFaultRepo();
    expect(await fault.can('delete_tx'), isFalse);
    await expectLater(fault.saveTx(_tx(accountId)), throwsA(anything));
    expect(await repo.transactions(), isEmpty);
  });

  for (final value in ['1.2.3', '١٫٢٫٣', '12..3']) {
    test('QA-FORMAT-01 ambiguous decimal $value is rejected', () {
      expect(Fmt.parseAmount(value), isNull);
    });
  }

  test(
      'QA-SYNC-01 queue states pending to syncing to synced with controlled transport',
      () async {
    // بعد إصلاح «المزامنات العالقة» لا يُدرج هدف Cloud إلا مع خادم مهيأ.
    await repo.setSetting('cloudBackendUrl', 'http://qa.local');
    final id = await repo.saveTx(_tx(accountId));
    final t = TestTransport()..gate = Completer<void>();
    engine.registerTransport(t);
    final work = engine.processQueue();
    await t.started.future;
    expect((await db.query('sync_queue')).single['status'], 'syncing');
    expect(
        (await db.query('transactions', where: 'id = ?', whereArgs: [id]))
            .single['sync_state'],
        'syncing');
    t.gate!.complete();
    await work;
    expect((await db.query('sync_queue')).single['status'], 'synced');
    expect((await repo.transactions()).single.syncState, 'synced');
    expect(t.calls, 1);
  });

  test('QA-SYNC-02 one failed push counts one attempt and retains local data',
      () async {
    await repo.setSetting('cloudBackendUrl', 'http://qa.local');
    await repo.saveTx(_tx(accountId));
    final t = TestTransport()..error = const SocketException('QA offline');
    engine.registerTransport(t);
    await engine.processQueue();
    final row = (await db.query('sync_queue')).single;
    expect(row['status'], 'pending');
    expect(row['attempts'], 1);
    expect(row['last_error'].toString(), contains('QA offline'));
    expect(row['next_try_at'], isNot(''));
    expect(await repo.transactions(), hasLength(1));
    await engine.processQueue();
    expect(t.calls, 1, reason: 'Backoff must prevent immediate retry');
  });

  test('QA-SYNC-03 الفشل ليس نهائيًا: العملية تبقى قيد إعادة المحاولة',
      () async {
    await repo.setSetting('cloudBackendUrl', 'http://qa.local');
    await repo.saveTx(_tx(accountId));
    await db.update('sync_queue', {'status': 'syncing', 'attempts': 99});
    final q = SyncQueueOps(db);
    final id = (await db.query('sync_queue')).single['id'] as int;
    // حتى بعد عدد ضخم من المحاولات، لا تُعلَّق العملية نهائيًا.
    await q.markFailed(id, 'QA offline');
    final row = (await db.query('sync_queue')).single;
    expect(row['status'], 'pending',
        reason: 'لا يوجد فشل نهائي — تبقى العملية في الانتظار للمحاولة تالية.');
    expect(row['last_error'].toString(), contains('QA offline'));
    // جدولتها المستقبلية بعد backoff قصير (≤ دقيقتين) ثم تُعاد تلقائيًا.
    expect(row['next_try_at'], isNot(''));
    // إعادة المحاولة اليدوية الفورية تصفّر الجدولة لتُدفع الآن.
    await q.retryNow(id: id);
    final reset = (await db.query('sync_queue')).single;
    expect(reset['next_try_at'], '');
    expect(reset['last_error'], '');
  });

  test('QA-SYNC-04 local save enqueues LAN when enabled', () async {
    await repo.setSetting('lanSyncEnabled', '1');
    await repo.saveTx(_tx(accountId));
    final rows = await db.query('sync_queue');
    expect(rows.map((r) => r['target']), contains(SyncTarget.lanBroadcast));
  });

  test('QA-SYNC-05 remote setting uses settings key rather than an id column',
      () async {
    final op = SyncOperation(
      id: 'qa-setting-op',
      deviceId: 'REMOTE',
      workspaceId: 'default',
      userId: null,
      parentOpId: '',
      entityType: EntityKind.setting,
      entityId: 'businessName',
      opType: OpKind.settings,
      version: 1,
      payload: {'key': 'businessName', 'value': 'شركة QA'},
      deviceTime: _now.toIso8601String(),
      timestamp: _now.toIso8601String(),
    );
    await db.transaction((txn) async {
      expect(
          await repo.applyRemoteOperation(txn, op, ConflictResolver()), isTrue);
    });
    expect((await repo.settings())['businessName'], 'شركة QA');
    final repeated = await db.transaction(
        (txn) => repo.applyRemoteOperation(txn, op, ConflictResolver()));
    expect(repeated, isFalse);
  });

  test('QA-SYNC-06 replaying a remote account operation is idempotent',
      () async {
    final op = SyncOperation(
      id: 'qa-account-op',
      deviceId: 'REMOTE',
      workspaceId: 'default',
      userId: null,
      parentOpId: '',
      entityType: EntityKind.account,
      entityId: '500',
      opType: OpKind.create,
      version: 1,
      payload: _account().toMap()..['id'] = 500,
      deviceTime: _now.toIso8601String(),
      timestamp: _now.toIso8601String(),
    );
    expect(
        await db.transaction(
            (txn) => repo.applyRemoteOperation(txn, op, ConflictResolver())),
        isTrue);
    expect(
        await db.transaction(
            (txn) => repo.applyRemoteOperation(txn, op, ConflictResolver())),
        isFalse);
    expect(await db.query('accounts', where: 'id = 500'), hasLength(1));
  });
}
